### ISSUE TITLE
Deployments fail on 0.34.0

### ISSUE THREAD

**Issue by mrkurt** [superfly/fly#100]
This seems to be different depending on user/app, but deploys frequently crash l with errors like this:

```
(node:70690) UnhandledPromiseRejectionWarning: Error: socket hang up
   at createHangUpError (_http_client.js:331:15)
   at TLSSocket.socketOnEnd (_http_client.js:423:23)
   at emitNone (events.js:111:20)
   at TLSSocket.emit (events.js:208:7)
   at endReadableNT (_stream_readable.js:1064:12)
   at _combinedTickCallback (internal/process/next_tick.js:138:11)
   at process._tickCallback (internal/process/next_tick.js:180:9)
(node:70690) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:70690) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The bundles aren't exceptionally big, and after installing 0.34.0-5 it works just fine.

**Comment by mrkurt** [comment]
Fixed in 0.35.0
