### ISSUE TITLE
NPM modules not working

### ISSUE THREAD

**Issue by SociallyDev** [superfly/fly#82]
Almost any module I download from NPM fails during Fly's compilation but works fine with normal node compilation.

Modules that I've tried: raven, then-request and mime.

I think the problem is with how these modules include their own modules, like raven uses require("console") which fails but if I edit it to require("./console.js"), it works.
Another error that occurs is that the default module fs isn't available.

Fly version: 0.33.1
Node version: 8.11.1

Here's the complete log (Only raven installed):

```
Using /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io as working directory.
Generating Webpack config...
Compiling app w/ options: { watch: true, uglify: false }
Server listening on :::3000
2018-05-25T15:29:45.677Z - info: Config watch (add: .fly.yml)
Error: Hash: 9dbeae32e43bfbe8bd27005eee4f7af3871d9087
Version: webpack 3.12.0
Time: 846ms
          Asset    Size  Chunks                    Chunk Names
      bundle.js  619 kB       0  [emitted]  [big]  main
bundle.map.json  759 kB       0  [emitted]  [big]  main
   [5] ./node_modules/raven/lib/utils.js 10.8 kB {0} [built]
   [8] /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/url/url.js 23.3 kB {0} [built]
  [14] ./node_modules/raven/vendor/json-stringify-safe.js 1.88 kB {0} [built]
  [15] ./node_modules/raven/lib/transports.js 2.76 kB {0} [built]
  [19] ./node_modules/raven/lib/parsers.js 4.56 kB {0} [built]
  [37] ./index.js 3.38 kB {0} [built]
  [38] ./node_modules/raven/index.js 274 bytes {0} [built]
  [39] ./node_modules/raven/lib/client.js 22.1 kB {0} [built]
  [41] /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/punycode/punycode.js 14.7 kB {0} [built]
  [43] /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/url/util.js 314 bytes {0} [built]
  [44] /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/querystring-es3/index.js 127 bytes {0} [built]
  [89] ./node_modules/mime/index.js 137 bytes {0} [built]
  [90] ./node_modules/mime/Mime.js 2.66 kB {0} [built]
  [91] ./node_modules/mime/types/standard.json 7.39 kB {0} [built]
  [92] ./node_modules/mime/types/other.json 24.6 kB {0} [built]
    + 78 hidden modules

ERROR in ./node_modules/raven/lib/instrumentation/instrumentor.js
Module not found: Error: Can't resolve 'console' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation'
resolve 'console' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation'
  Parsed request is a module
  using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib/instrumentation)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib/instrumentation)
    resolve as module
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules
        using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules/console)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console.js doesn't exist
            as directory
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console doesn't exist
      looking for modules in /Users/devangsrivastava/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/console doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/console.js doesn't exist
        as directory
          /Users/devangsrivastava/node_modules/console doesn't exist
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules]
[/Users/devangsrivastava/Desktop/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/devangsrivastava/node_modules/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console.js]
[/Users/devangsrivastava/node_modules/console/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/console]
[/Users/devangsrivastava/node_modules/console]
[/Users/devangsrivastava/node_modules/console.js]
[/Users/devangsrivastava/node_modules/console]
 @ ./node_modules/raven/lib/instrumentation/instrumentor.js 47:4-22
 @ ./node_modules/raven/lib/client.js
 @ ./node_modules/raven/index.js
 @ ./index.js

ERROR in ./node_modules/raven/lib/utils.js
Module not found: Error: Can't resolve 'fs' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib'
resolve 'fs' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib'
  Parsed request is a module
  using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib)
    resolve as module
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules
        using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs.js doesn't exist
            as directory
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs doesn't exist
      looking for modules in /Users/devangsrivastava/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/fs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/fs.js doesn't exist
        as directory
          /Users/devangsrivastava/node_modules/fs doesn't exist
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules]
[/Users/devangsrivastava/Desktop/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/devangsrivastava/node_modules/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs.js]
[/Users/devangsrivastava/node_modules/fs/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs]
[/Users/devangsrivastava/node_modules/fs]
[/Users/devangsrivastava/node_modules/fs.js]
[/Users/devangsrivastava/node_modules/fs]
 @ ./node_modules/raven/lib/utils.js 3:9-22
 @ ./node_modules/raven/index.js
 @ ./index.js

ERROR in ./node_modules/raven/vendor/node-lsmod.js
Module not found: Error: Can't resolve 'fs' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/vendor'
resolve 'fs' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/vendor'
  Parsed request is a module
  using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./vendor)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./vendor)
    resolve as module
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/vendor/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules
        using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules/fs)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs.js doesn't exist
            as directory
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs doesn't exist
      looking for modules in /Users/devangsrivastava/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/fs doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/fs.js doesn't exist
        as directory
          /Users/devangsrivastava/node_modules/fs doesn't exist
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/vendor/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules]
[/Users/devangsrivastava/Desktop/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/devangsrivastava/node_modules/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs.js]
[/Users/devangsrivastava/node_modules/fs/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/fs]
[/Users/devangsrivastava/node_modules/fs]
[/Users/devangsrivastava/node_modules/fs.js]
[/Users/devangsrivastava/node_modules/fs]
 @ ./node_modules/raven/vendor/node-lsmod.js 8:9-22
 @ ./node_modules/raven/lib/utils.js
 @ ./node_modules/raven/index.js
 @ ./index.js

ERROR in ./node_modules/raven/lib/instrumentation/instrumentor.js
Module not found: Error: Can't resolve 'module' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation'
resolve 'module' in '/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation'
  Parsed request is a module
  using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib/instrumentation)
    Field 'browser' doesn't contain a valid alias configuration
  after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/package.json (relative path: ./lib/instrumentation)
    resolve as module
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules doesn't exist or is not a directory
      /Users/devangsrivastava/Desktop/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
      looking for modules in /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules
        using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          Field 'browser' doesn't contain a valid alias configuration
        after using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules)
          using description file: /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/package.json (relative path: ./node_modules/module)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module.js doesn't exist
            as directory
              /Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module doesn't exist
      looking for modules in /Users/devangsrivastava/node_modules
        No description file found
        Field 'browser' doesn't contain a valid alias configuration
        No description file found
        no extension
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/module doesn't exist
        .js
          Field 'browser' doesn't contain a valid alias configuration
          /Users/devangsrivastava/node_modules/module.js doesn't exist
        as directory
          /Users/devangsrivastava/node_modules/module doesn't exist
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/instrumentation/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/lib/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/raven/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/node_modules]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/node_modules]
[/Users/devangsrivastava/Desktop/node_modules]
[/Users/node_modules]
[/node_modules]
[/Users/devangsrivastava/node_modules/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module.js]
[/Users/devangsrivastava/node_modules/module/package.json]
[/Users/devangsrivastava/Desktop/HyperBoost Builds/Fly + Spaces + Fly Cache PRODUCTION.io/node_modules/module]
[/Users/devangsrivastava/node_modules/module]
[/Users/devangsrivastava/node_modules/module.js]
[/Users/devangsrivastava/node_modules/module]
 @ ./node_modules/raven/lib/instrumentation/instrumentor.js 28:15-32
 @ ./node_modules/raven/lib/client.js
 @ ./node_modules/raven/index.js
 @ ./index.js
    at Watching.handler (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/src/utils/build.ts:41:16)
    at Watching._done (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:106:8)
    at compiler.emitRecords.err (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:79:19)
    at Compiler.emitRecords (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:371:38)
    at compiler.emitAssets.err (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:62:20)
    at applyPluginsAsyncSeries1.err (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:364:12)
    at next (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:361:9)
    at require.forEach.err (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/webpack/lib/Compiler.js:350:15)
    at /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/async/dist/async.js:473:16
    at iteratorCallback (/Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/async/dist/async.js:1064:13)
    at /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/async/dist/async.js:969:16
    at /Users/devangsrivastava/.nvm/versions/node/v8.11.1/lib/node_modules/@fly/fly/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)

```

**Comment by pudility** [comment]
I think this has to do with how fly uses an isolated v8 environment - I am not sure there is a really good way to add npm modules other than hacking fly a little bit but, I could be wrong about this.

**Comment by SociallyDev** [comment]
@mrkurt That clears things up a lot, I'll make the necessary changes in my code.

The problem with mime was the same (nested) module not found error, so I fixed it by changing its require statements' paths like require('./types/standard') to exact file paths like require('./types/standard.json').

I'd love to see more documentation on Fly's environment in the future.
Thank you.
